
Use HotelBookingApp;

SELECT * FROM Guests;
SELECT * FROM Rooms;
SELECT * FROM Bookings;
SELECT * FROM Payments;


SELECT * 
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
WHERE DELETE_RULE = 'CASCADE';
